"""Add status field to ProductivityEvent

Revision ID: 093f11a9b8c0
Revises: af37a902573e
Create Date: 2026-05-15 19:41:07.666151

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '093f11a9b8c0'
down_revision = 'af37a902573e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_chat_messages_created_at'))
        batch_op.drop_index(batch_op.f('idx_chat_messages_session_id'))
        batch_op.create_index(batch_op.f('ix_chat_messages_session_id'), ['session_id'], unique=False)

    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_server_default=sa.text("'New Chat'::character varying"))
        batch_op.drop_index(batch_op.f('idx_chat_sessions_user_id'))
        batch_op.create_index(batch_op.f('ix_chat_sessions_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('journals', schema=None) as batch_op:
        batch_op.alter_column('emojis',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::text[]"))
        batch_op.create_index(batch_op.f('ix_journals_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('productivity_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False, server_default=sa.text("'To Do'")))
        batch_op.alter_column('color',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=7),
               existing_nullable=True,
               existing_server_default=sa.text("'#6366f1'::character varying"))
        batch_op.drop_index(batch_op.f('idx_productivity_user_date'))
        batch_op.create_index(batch_op.f('ix_productivity_events_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productivity_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_productivity_events_user_id'))
        batch_op.create_index(batch_op.f('idx_productivity_user_date'), ['user_id', 'event_date'], unique=False)
        batch_op.alter_column('color',
               existing_type=sa.String(length=7),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'#6366f1'::character varying"))
        batch_op.drop_column('status')

    with op.batch_alter_table('journals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journals_user_id'))
        batch_op.alter_column('emojis',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True,
               existing_server_default=sa.text("'{}'::text[]"))

    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_sessions_user_id'))
        batch_op.create_index(batch_op.f('idx_chat_sessions_user_id'), ['user_id'], unique=False)
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text("'New Chat'::character varying"))

    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_messages_session_id'))
        batch_op.create_index(batch_op.f('idx_chat_messages_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_chat_messages_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###
