"""Add habit_goals table

Revision ID: 0e359f7b5939
Revises: e5f6g7h8i9j0
Create Date: 2026-05-17 20:43:06.378645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e359f7b5939'
down_revision = 'e5f6g7h8i9j0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('habit_goals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('current_progress', sa.Integer(), nullable=False),
    sa.Column('target', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('habit_goals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_habit_goals_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('habit_goals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_habit_goals_user_id'))

    op.drop_table('habit_goals')
    # ### end Alembic commands ###
